
        #     name=input("Enter Name : ")
        #     age=int(input("Enter age  : "))
        #     print()
        #     student=(name,age)
        #     students.append(student)
        #     choice=input("Do you wanna add another name (Y/N): ")
        #     if choice.upper()=="N":
        #          break
            
        # cursor.executemany("INSERT INTO student(name,age) VALUES(%s,%s)",students)
        # total_rows=cursor.rowcount